git config alias.br branch
git config alias.bra branch
git config alias.co checkout
git config alias.ch checkout
git config alias.st status
git config alias.stus status
git config alias.com commit
git config alias.comi commit
git config alias.comm commit
git config alias.lo log